
pipelines:
  default:
    - step:
        name: Build and test
        deployment: staging
        image: node:10.16.0
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - rm -rvf node_modules
          - npm install
          - mkdir staging
          - cd staging
          - git init
          - git remote add origin https://ktmtimetable:4e1effb21ce72e66c7ce54c0935ff1cbf1f8eb73@github.com/nclong87/ktmtimetable-staging.git
          - git fetch
          - git pull origin gh-pages
          - ls
          - cd ..
          - npm run build-staging
        artifacts:
          - staging/**
    - step:
        name: Deploy to Github Pages
        script:
          - cd staging
          - git add .
          - git config --global user.email "ktmtimetable@gmail.com"
          - git config --global user.name "KTM Timetable"
          - git commit -m "Publish"
          - git push origin gh-pages
