
pipelines:
  default:
    - step:
        name: Build and test
        deployment: staging
        image: node:10.16.0
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - rm -rvf node_modules
          - npm install
          - npm run build-staging
        artifacts:
          - staging/**
    - step:
        name: Deploy to Github Pages
        image: node:10.16.0
        caches:
          - node
        script:
          - git remote set-url https://ktmtimetable:WyViU5M6NLneqTUg@github.com/nclong87/ktmtimetable-staging.git
          - npm run deploy-staging
