
pipelines:
  default:
    - step:
        name: Deploy to Github Pages
        image: node:10.16.0
        caches:
          - node
        script:
          - git config --global credential.helper libsecret
          - npm run deploy-staging
