
pipelines:
  branches:
    staging:
      - step:
          name: Build in Staging
          deployment: staging
          image: node:10.16.0
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - rm -rvf node_modules
            - npm install
            - mkdir staging
            - cd staging
            - git init
            - git remote add origin $GITHUB_URL
            - git fetch
            - git pull origin gh-pages
            - ls
            - cd ..
            - npm run build-staging
          artifacts:
            - staging/**
      - step:
          name: Deploy to Github Pages
          script:
            - cd staging
            - git checkout gh-pages
            - git add .
            - git status
<<<<<<< HEAD
=======
            - git config --global user.email "ktmtimetable@gmail.com"
            - git config --global user.name "KTM Timetable"
            - git commit -m "Publish build `#$BITBUCKET_BUILD_NUMBER"
            - git push origin gh-pages
>>>>>>> master
    master:
      - step:
          name: Build in Production
          deployment: production
          image: node:10.16.0
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - rm -rvf node_modules
            - npm install
            - mkdir prod
            - cd prod
            - git init
            - git remote add origin $GITHUB_URL
            - git fetch
            - git pull origin gh-pages
            - ls
            - cd ..
            - npm run build-prod
          artifacts:
            - prod/**
      - step:
          name: Deploy to Github Pages
          script:
            - cd prod
            - git checkout gh-pages
            - git add .
            - git status
            - git config --global user.email "ktmtimetable@gmail.com"
            - git config --global user.name "KTM Timetable"
            - git commit -m "Build number $BITBUCKET_BUILD_NUMBER"
            - git tag $BITBUCKET_BUILD_NUMBER
            - git push origin $BITBUCKET_BUILD_NUMBER
            - git push origin gh-pages
