
pipelines:
  default:
    - step:
        name: Build and test
        image: node:10.16.0
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - rm -rvf node_modules
          - npm install
          - npm run build-staging
        artifacts:
          - staging/**
    - step:
        name: Deploy to Github Pages
        image: node:10.16.0
        caches:
          - node
        dependencies:
          - staging
        script:
          - git config user.name "ktmtimetable@gmail.com"
          - git config user.password "WyViU5M6NLneqTUg"
          - npm run deploy-staging
